# Generated by Django 2.1.15 on 2020-05-04 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200501_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_minutes',
            new_name='time_in_minutes',
        ),
    ]
